language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/travis-testtap
  - brew tap --repair
env:
  - PACKAGE=applgrid
  - PACKAGE=fastjet
  - PACKAGE=fastnlo
  - PACKAGE=fjcontrib
  - PACKAGE=hepmc
  - PACKAGE=herwig++
  - PACKAGE=hoppet
  - PACKAGE=jetvheto
  - PACKAGE=lhapdf
  - PACKAGE=madgraph5_amcatnlo
  - PACKAGE=mcfm
  - PACKAGE=mcgrid
  - PACKAGE=pythia8
  - PACKAGE=qcdnum
  - PACKAGE=rivet
  - PACKAGE=sacrifice
  - PACKAGE=sherpa
  - PACKAGE=thepeg
  - PACKAGE=whizard
  - PACKAGE=yoda
script:
  - if [ "$PACKAGE" != "qcdnum" ]; then brew audit $PACKAGE; fi
  - brew install -v $PACKAGE
