language: objective-c
before_install:
  - brew update
  - brew install gfortran
  - brew tap homebrew/science
install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/travis-testtap
  - brew tap --repair
env:
  - PACKAGE=amcatnlo
  - PACKAGE=applgrid
  - PACKAGE=fastjet
  - PACKAGE=fjcontrib
  - PACKAGE=hepmc
  - PACKAGE=herwig++
  - PACKAGE=hoppet
  - PACKAGE=jetvheto
  - PACKAGE=lhapdf
  - PACKAGE=madgraph
  - PACKAGE=mcfm
  - PACKAGE=pythia8
  - PACKAGE=qcdnum
  - PACKAGE=rivet
  - PACKAGE=sacrifice
  - PACKAGE=sherpa
  - PACKAGE=thepeg
  - PACKAGE=yoda
script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - '! brew cat $PACKAGE | grep -q "test do" || brew test -v $PACKAGE'
